[sections]
1 = "Commands"
2 = "System Calls"
3 = "Libraries"
4 = "File Formats"
5 = "Standards, Environments, and Macros"
6 = "There Is Nooooooooo... Section 6"
7 = "Device and Network Interfaces"
8 = "This Section Intentionally Left Blank"
9 = "Driver Entry Points"

[subsections]
1 = "User Commands"
1b = "SunOS/BSD Compatibility Package Commands"
1c = "Communication Commands"
1m = "Maintenance Commands"
2 = "System Calls"
3 = "Introduction to Library Functions"
3bsm = "Security and Auditing Library Functions"
3c = "Standard C Library Functions"
3cfgadm = "Configuration Administration Library Functions"
3contract = "Contract Subsystem Interfaces"
3curses = "Curses Library Functions"
3xnet = "X/Open Networking Interfaces"
3libucb = "SunOS/BSD Compatibility Libraries"
4 = "File Formats"
5 = "Standards, Environments, and Macros"
7 = "Device and Network Interfaces"
7d = "Devices"
7fs = "File Systems"
7i = "ioctl Requests"
7ipp = "Miscellaneous References"
7m = "STREAMS Modules"
7p = "Protocols"
9e = "Driver Entry Points"
9f = "Kernel Functions"
9p = "Driver Properties"
9s = "Data Structures"
