[sections]
1 = "User Commands"
2 = "System Calls"
3 = "Libraries"
4 = "Device and Network Interfaces"
5 = "File Formats and Configurations"
6 = "Games and Demos"
7 = "Standards, Environments, and Macros"
8 = "Maintenance Commands and Procedures"
9 = "Kernel Concepts"

[subsections]
1 = "User Commands"
1B = "BSD Compatibility Package Commands"
1C = "Communication Commands"
1HAS = "User Commands"
1ONBLD = "illumos Build Tools"
1S = "illumos Specific Commands"
2 = "System Calls"
3 = "Introduction to Library Functions"
3AVL = "AVL Tree Library Functions"
3BSDMALLOC = "BSD Memory Allocation Library"
3BSM = "Security and Auditing Library Functions"
3C = "Standard C Library Functions"
"3C++" = "C++ Library Functions"
3C_DB = "Threads Debugging Library Functions"
3CFGADM = "Configuration Administration Library Functions"
3COMMPUTIL = "Communication Protocol Parser Utilities Library Functions"
3CONTRACT = "Contract Management Library Functions"
3CPC = "CPU Performance Counters Library Functions"
3CURSES = "Curses Library Functions"
3DAT = "Direct Access Transport Library Functions"
3DEVID = "Device ID Library Functions"
3DEVINFO = "Device Information Library Functions"
3DLPI = "Data Link Provider Interface Library Functions"
3DNS_SD = "DNS Service Discovery Library Functions"
3DOOR = "Door Library Functions"
3ELF = "ELF Library Functions"
3EXACCT = "Extended Accounting File Access Library Functions"
3EXT = "Extended Library Functions"
3FCOE = "FCoE Port Management Library Functions"
3FSTYP = "File System Type Identification Library Functions"
3GEN = "String Pattern-Matching Library Functions"
3GSS = "Generic Security Services API Library Functions"
3HEAD = "Headers"
3ISCSIT = "iSCSI Management Library Functions"
3KRB = "Kerberos Library Functions"
3KRB5 = "MIT Kerberos 5 Library Functions"
3KSTAT = "Kernel Statistics Library Functions"
3KVM = "Kernel VM Library Functions"
3LDAP = "LDAP Library Functions"
3LGRP = "Locality Group Library Functions"
3LIB = "Interface Libraries"
3M = "Mathematical Library Functions"
3MAIL = "User Mailbox Library Functions"
3MALLOC = "Memory Allocation Library Functions"
3MP = "Multiple Precision Library Functions"
3MPAPI = "Common Multipath Management Library Functions"
3NSL = "Networking Services Library Functions"
3NVPAIR = "Name-value Pair Library Functions"
3OFMT = "Formatted Output Functions"
3PAM = "PAM Library Functions"
3PAPI = "PAPI Library Functions"
3PERL = "Perl Library Functions"
3PICL = "PICL Library Functions"
3PICLTREE = "PICL Plug-In Library Functions"
3POOL = "Pool Configuration Manipulation Library Functions"
3PROC = "Process Control Library Functions"
3PROJECT = "Project Database Access Library Functions"
3RAC = "Remote Asynchronous Calls Library Functions"
3RESOLV = "Resolver Library Functions"
3RPC = "RPC Library Functions"
3RSM = "Remote Shared Memory Library Functions"
3RT = "Realtime Library Functions"
3SASL = "Simple Authentication Security Layer Library Functions"
3SCF = "Service Configuration Facility Library Functions"
3SEC = "File Access Control Library Functions"
3SECDB = "Security Attributes Database Library Functions"
3SIP = "Session Initiation Protocol Library Functions"
3SLP = "Service Location Protocol Library Functions"
3SOCKET = "Sockets Library Functions"
3STMF = "SCSI Target Mode Framework Library Functions"
3SYSEVENT = "System Event Library Functions"
3TECLA = "Interactive Command-line Input Library Functions"
3TNF = "TNF Library Functions"
3TSOL = "Trusted Extensions Library Functions"
3UTEMPTER = "UTEMPTER Library Functions"
3UUID = "Universally Unique Identifier Library Functions"
3VOLMGT = "Volume Management Library Functions"
3XCURSES = "X/Open Curses Library Functions"
3XNET = "X/Open Networking Services Library Functions"
3F = "Fortran Library Routines"
3X = "Miscellaneous Library Functions"
4 = "Device and Network Interfaces"
4D = "Devices"
4FS = "File Systems"
4I = "Ioctl Requests"
4IPP = "IP Quality of Service Modules"
4M = "STREAMS Modules"
4P = "Protocols"
5 = "File Formats and Configurations"
6 = "Games and Demos"
7 = "Standards, Environments, and Macros"
8 = "Maintenance Commands and Procedures"
9 = "Kernel Concepts"
9E = "Driver Entry Points"
9F = "Kernel Functions for Drivers"
9P = "Kernel Properties for Drivers"
9S = "Data Structures for Drivers"
